# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='UnitPrice')),
            ],
        ),
    ]
